"""
PPO for the constructive placement policy (Track B, and Track D when
--instances random).

One rollout is exactly one episode (n placements), so GAE is never truncated and
gamma=1 is unbiased: the return of an episode is the objective of the layout it
produced, minus the constant partial objective of the empty layout.
"""

import argparse
import json
import os
import sys
import time

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import core                                                   # noqa: E402
from construct_env import ConstructEnv, N_PLANES, N_GLOB_C    # noqa: E402
from nets import ConstructPolicy                              # noqa: E402
from train_improve import RunningNorm                         # noqa: E402


def make_env(args, seed, batch=None):
    B = batch or args.n_envs
    if args.instances == "fixed":
        from layout_env import build_spec
        spec = build_spec(args.scenario, flip_adj=args.flip_adj)
        inst = core.from_spec(spec, B)
        resample, canvas = None, None
    elif args.instances == "bench":
        # The benchmark suite of Section 6.3 is generated by guillotine
        # partition, which differs from `core.generate_instances` in how room
        # sizes arise and in decoupling size from type.  A policy evaluated on
        # that suite must be trained on its *train* split, or the comparison
        # confounds distribution shift with the value of learning.  Fill ratios
        # are drawn per batch across the suite's range.
        import bench
        canvas = args.canvas
        fills = [float(f) for f in args.bench_fills]

        def _draw(rng):
            f = fills[int(rng.integers(len(fills)))]
            i, _, _ = bench.make_instances(B, args.n_rooms, f, rng,
                                           max_grid=canvas, jitter_weights=True)
            return i

        base = np.random.default_rng(seed + bench.SPLIT_OFFSET["train"] + 999)
        inst = _draw(base)
        resample = _draw
    else:
        canvas = args.canvas
        gen = dict(max_grid=canvas, jitter_weights=True)
        inst = core.generate_instances(B, args.n_rooms,
                                       np.random.default_rng(seed + 999), **gen)

        def resample(rng):
            return core.generate_instances(B, args.n_rooms, rng, **gen)
    return ConstructEnv(inst, seed=seed, resample=resample, order=args.order,
                        canvas=canvas)


def train(args):
    dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    env = make_env(args, args.seed)
    n, B = env.n, env.B
    GH, GW = env.GH, env.GW
    model = ConstructPolicy(env.feat_dim, N_GLOB_C, N_PLANES, d_model=args.d_model,
                            n_blocks=args.n_blocks, ch=args.ch).to(dev)
    opt = torch.optim.Adam(model.parameters(), lr=args.lr, eps=1e-5)
    norm = RunningNorm(env.feat_dim)

    n_iters = max(1, args.total_steps // (B * n))
    history, t0 = [], time.time()
    print(f"[{args.tag}] constructive: n={n} B={B} canvas={GH}x{GW} "
          f"instances={args.instances} order={args.order} -> {n_iters} iters", flush=True)

    T = torch.as_tensor
    for it in range(1, n_iters + 1):
        obs, glob = env.reset(new_instance=args.instances != "fixed")
        norm.update(obs)
        buf = {
            "obs": np.zeros((n, B, n, env.feat_dim), dtype=np.float32),
            "glob": np.zeros((n, B, N_GLOB_C), dtype=np.float32),
            "rmask": np.zeros((n, B, n), dtype=bool),
            "planes": np.zeros((n, B, N_PLANES, GH, GW), dtype=np.float16),
            "legal": np.zeros((n, B, GH, GW), dtype=bool),
            "dead": np.zeros((n, B), dtype=bool),
            "room": np.zeros((n, B), dtype=np.int64),
            "pos": np.zeros((n, B), dtype=np.int64),
            "logp": np.zeros((n, B), dtype=np.float32),
            "val": np.zeros((n, B), dtype=np.float32),
            "rew": np.zeros((n, B), dtype=np.float32),
        }

        for t in range(n):
            nobs = norm(obs)
            rmask = ~env.placed
            cache = {}

            def planes_fn(room_np):
                P, legal, dead, fb = env.planes(room_np)
                cache["P"], cache["legal"], cache["dead"], cache["fb"] = P, legal, dead, fb
                return (T(P, device=dev), T(legal, device=dev), T(dead, device=dev))

            fr = env.forced_room()
            with torch.no_grad():
                a = model.act(T(nobs, device=dev), T(glob, device=dev),
                              T(rmask, device=dev), planes_fn, deterministic=False,
                              forced_room=None if fr is None else T(fr, device=dev))
            room = a["room"].cpu().numpy()
            pos = a["pos"].cpu().numpy()
            # rooms with no legal cell are placed at the least-overlapping one
            if cache["dead"].any():
                fb = cache["fb"].reshape(B, -1).argmax(axis=1)
                pos = np.where(cache["dead"], fb, pos)

            buf["obs"][t], buf["glob"][t], buf["rmask"][t] = nobs, glob, rmask
            buf["planes"][t] = cache["P"].astype(np.float16)
            buf["legal"][t], buf["dead"][t] = cache["legal"], cache["dead"]
            buf["room"][t], buf["pos"][t] = room, pos
            buf["logp"][t] = a["logp"].cpu().numpy()
            buf["val"][t] = a["value"].cpu().numpy()

            obs, glob, rew, done = env.step(room, pos)
            norm.update(obs)
            buf["rew"][t] = rew

        # GAE over one complete episode; bootstrap value is 0 at the terminal state
        adv = np.zeros((n, B), dtype=np.float32)
        lastgae = 0.0
        for t in reversed(range(n)):
            nextval = 0.0 if t == n - 1 else buf["val"][t + 1]
            delta = buf["rew"][t] + args.gamma * nextval - buf["val"][t]
            lastgae = delta + args.gamma * args.lam * lastgae
            adv[t] = lastgae
        ret = adv + buf["val"]

        f = {k: v.reshape((-1,) + v.shape[2:]) for k, v in buf.items()}
        N = n * B
        d_obs = T(f["obs"], device=dev)
        d_glob = T(f["glob"], device=dev)
        d_rmask = T(f["rmask"], device=dev)
        d_planes = T(f["planes"], device=dev)
        d_legal = T(f["legal"], device=dev)
        d_dead = T(f["dead"], device=dev)
        d_room = T(f["room"], device=dev)
        d_pos = T(f["pos"], device=dev)
        d_logp = T(f["logp"], device=dev)
        d_adv = T(adv.reshape(-1), device=dev)
        d_ret = T(ret.reshape(-1), device=dev)
        d_adv = (d_adv - d_adv.mean()) / (d_adv.std() + 1e-8)

        idx = np.arange(N)
        # The entropy floor is the quality/diversity knob.  Annealing it to ~0
        # (the usual default) produces a policy that is a deterministic
        # constructor: excellent layouts, but one layout per brief.  Holding it
        # up keeps the policy a distribution, at some cost in mean objective.
        ent_coef = args.ent_coef * max(args.ent_floor, 1.0 - it / (0.8 * n_iters))
        for _ in range(args.epochs):
            np.random.shuffle(idx)
            for s in range(0, N, args.minibatch):
                mb = T(idx[s:s + args.minibatch], device=dev)
                logp, ent, val = model.evaluate(
                    d_obs[mb], d_glob[mb], d_rmask[mb], d_planes[mb].float(),
                    d_legal[mb], d_dead[mb], d_room[mb], d_pos[mb],
                    forced=args.order != "policy")
                ratio = (logp - d_logp[mb]).exp()
                A = d_adv[mb]
                pi_loss = -torch.min(ratio * A,
                                     torch.clamp(ratio, 1 - args.clip, 1 + args.clip) * A).mean()
                loss = pi_loss + args.vf_coef * F.mse_loss(val, d_ret[mb]) - ent_coef * ent.mean()
                opt.zero_grad(set_to_none=True)
                loss.backward()
                nn.utils.clip_grad_norm_(model.parameters(), args.max_grad_norm)
                opt.step()

        _, _, tot, c = env.result()
        rec = {"iter": it, "steps": it * B * n,
               "J": float(tot.mean()), "J_max": float(tot.max()),
               "J_frac": float((tot / env.ceil).mean()),
               "feasible": float(np.mean(c["overlap_area"] <= 1e-9)),
               "adj": float(c["adj"].mean()), "edge": float(c["edge"].mean()),
               "elapsed": time.time() - t0}
        history.append(rec)
        if it % args.log_every == 0 or it == n_iters:
            print(f"[{args.tag}] it {it}/{n_iters} J={rec['J']:.1f} max={rec['J_max']:.1f} "
                  f"J/ceil={rec['J_frac']:.4f} feas={rec['feasible']:.2f} "
                  f"adj={rec['adj']:.0f} edge={rec['edge']:.1f} ({rec['elapsed']:.0f}s)",
                  flush=True)

    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, f"{args.tag}.pt")
    torch.save({"model": model.state_dict(), "norm": norm.state(), "args": vars(args)}, path)
    with open(os.path.join(args.out, f"{args.tag}_history.json"), "w") as f_:
        json.dump(history, f_, indent=1)
    print(f"[{args.tag}] saved {path} ({time.time()-t0:.0f}s)", flush=True)
    return path


def get_parser():
    p = argparse.ArgumentParser()
    p.add_argument("--tag", default="construct")
    p.add_argument("--scenario", default="comb_high")
    p.add_argument("--flip-adj", dest="flip_adj", action="store_true", default=True)
    p.add_argument("--no-flip-adj", dest="flip_adj", action="store_false")
    p.add_argument("--instances", default="fixed",
                   choices=["fixed", "random", "bench"])
    p.add_argument("--bench-fills", dest="bench_fills", nargs="+", type=float,
                   default=[0.40, 0.60, 0.75])
    p.add_argument("--n-rooms", dest="n_rooms", type=int, default=32)
    p.add_argument("--canvas", type=int, default=44,
                   help="fixed canvas for instance-distribution training")
    p.add_argument("--order", default="policy", choices=["policy", "area", "random"])
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--total-steps", dest="total_steps", type=int, default=3_000_000)
    p.add_argument("--n-envs", dest="n_envs", type=int, default=128)
    p.add_argument("--gamma", type=float, default=1.0)
    p.add_argument("--lam", type=float, default=0.95)
    p.add_argument("--clip", type=float, default=0.2)
    p.add_argument("--epochs", type=int, default=3)
    p.add_argument("--minibatch", type=int, default=512)
    p.add_argument("--lr", type=float, default=3e-4)
    p.add_argument("--ent-coef", dest="ent_coef", type=float, default=0.01)
    p.add_argument("--ent-floor", dest="ent_floor", type=float, default=0.05,
                   help="entropy coefficient floor as a fraction of --ent-coef; "
                        "raise it to trade objective for solution variety")
    p.add_argument("--vf-coef", dest="vf_coef", type=float, default=0.5)
    p.add_argument("--max-grad-norm", dest="max_grad_norm", type=float, default=0.5)
    p.add_argument("--d-model", dest="d_model", type=int, default=128)
    p.add_argument("--n-blocks", dest="n_blocks", type=int, default=3)
    p.add_argument("--ch", type=int, default=64)
    p.add_argument("--log-every", dest="log_every", type=int, default=10)
    p.add_argument("--out", default="runs")
    return p


if __name__ == "__main__":
    train(get_parser().parse_args())
